### ISSUE TITLE
Add time elapsed feature in the client

### ISSUE THREAD

**Issue by pandeynmn** [kingbri1/Universal-RPC#6]
Add time elapsed feature in the client, discord uses 
    discordPresence.startTimestamp = 1507665886; <- epoch time stamp
    discordPresence.endTimestamp = 1507665886;
and there should exist something in the js lib for this method

Additionally, we can also add a method to convert epoch time stamp to current time and make other functions as well for the ease of user.

**Comment by kingbri1** [comment]
Issue closed, JS lib needed `startTimestamp`
